name: Pull Request
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  release:
    name: Pull Request
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GH_PAT }}
