name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Release with semantic release"
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
